version: '3.5'

services:
  users:
    build:
      context: ${REL_PATH_USERS:-.}/
      dockerfile: ./docker/Dockerfile
    image: users
    container_name: ${APP_NAME}_users
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - ${REL_PATH_USERS:-.}/:/var/www/app
  nginx_users:
    image: nginx:alpine
    container_name: ${APP_NAME}_users_nginx
    restart: unless-stopped
    ports:
    - 8181:80
    volumes:
      - ${REL_PATH_USERS:-.}/:/var/www/app
      - ${REL_PATH_USERS:-.}/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - users
  db_users:
    image: mysql:8
    container_name: db_users
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker/db_users:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_users
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${APP_NAME}_rabbitmq
    volumes:
      #- ./docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
  worker_users_failings_broker_jobs:
    build:
      context: ${REL_PATH_USERS:-.}/
      dockerfile: ./docker/Dockerfile
    image: users
    container_name: ${APP_NAME}_worker_users_failings_broker_jobs
    restart: unless-stopped
    working_dir: /var/www/app
    command: 'sh -c "sleep 10 && php artisan broker_fails_handler:start"'
    volumes:
      - ${REL_PATH_USERS:-.}/:/var/www/app
    depends_on:
      - rabbitmq
      - users
networks:
  default:
    name: microservices
